language: python
python:
  - 3.5
services:
  - postgresql
before_install:
  - psql -c 'CREATE DATABASE ccdbdjango;' -U postgres
  - export DJANGO_SETTINGS_MODULE=config.settings.local
  - export DATABASE_URL=postgres://postgres@localhost/ccdbdjango
install:
  - pip install -r requirements/local.txt
  - pip install coveralls
script:
  - python manage.py migrate
  - flake8 --exclude=migrations,settings,manage.py,misc/existing.py
  - coverage run --rcfile .coveragerc manage.py test
after_success:
  - coveralls
deploy:
  provider: heroku
  app: obscure-caverns-99102
  run: "python manage.py migrate"
  api_key:
    secure: W/0S2QKOGYXOeqAiBy7VSpHFMqKTNFfsB8QtTGVs3ZOCwKGf3bRPWBEDW9hmLsQo8jG5vUR8maJ7xPUMqMzzzcMRnBewX0p+PZbXsdtm4+9t1+7o8Ych1pGRKC9JUueEOwLzSoLYzBYVvg45GFTd6L0yblp8BwKxSBkfBrNOiCKH7AqvtiHtDhzbsBL3utx3UbeKuJxNCbEuIwp/chQj3RwH8cPq6mqeWB7ZJBC5vwUxz4Q9XX6j27c4bIwoGTrCXWHDq0zBHuR+KGvR4BZlcyh6VYgT97hYn0mcVe7YTBIrhWWkubJCmSE5xzWhhKO4LWqbR6TbDw6wthp9nbEIXrXyNAZoIIJhbhIKaEr7+3Zx6I3OMIPNcKqFv4jIpjZf2GfIbf/uW4iCABbkHafqjse7pltQBfQbNyCp7FxlJImWsJ9/0VJ3nA6Hm5VrG2nUSgVnBJjU76AKKtkNS6iyP150xVjoQbq1rPd2HZBCsu4vz7zFq5VsMHD/d7fXCX3EWnFjS0u+0c8M84SVasycQKq4tZcVj4CETHLLBc6yqyeWGdtikWnDEEeGyutqjL5Qr6qq+itcg0jGZXD9Wia+i4dh/8CgyNABYUT/tM2yf6sLA08x33jFoHSZCokrcRShOrn0sSt7G2H3tRoSOrwCUc8GlBN2dn4kH2gBVwm0jTc=
